name: montrack
description: 'Montrack App Money Management'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  go_router: ^16.0.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.8.0+1
  logger: ^2.6.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  skeletonizer: ^2.1.0+1
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  emoji_picker_flutter: ^4.3.0
  loader_overlay: ^5.0.0
  flutter_otp_text_field: ^1.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  freezed: ^3.1.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  background_image: "assets/background.png"
  image: "assets/logo.png"
  branding: "assets/branding_logo.png"

  android_12:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: "assets/logo.png"
    branding: "assets/branding_logo.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"
